### PR TITLE
make pdm support compatible with pdm 2.8

### LINKED ISSUE #39: This project is incompatible with the pdm 2.8 lock format
Before loading the `pdm.lock` file it would be great to first check that the lock version is compatible with what `rules_pycross` supports. `pdm 2.8` which was released last week drastically changes the format and the rules_pycross is now failing with slightly difficult to understand errors.

### PR DESCRIPTION
**Pull request by betaboon**
resolves #39

### CODE REVIEW

**Comment by jvolkman** [comment]
Does this break compatibility with previous lockfile versions? I don't think that's a blocker if so, just curious.

**Comment by betaboon** [comment]
yes i think it does.

**Comment by betaboon** [comment]
@jvolkman i just rebased and added another fix (pytorch has started to use `pytorch%2bcpu` instead of `pytorch+cpu`)
this fix seems to still work with latest pdm.
can we get this merged somehow?

**Comment by jvolkman** [comment]
Thanks for working on it @betaboon. I'll look at merging today.

**Pull request merged**
